#============================================================================
# DATABASE
#============================================================================
db:
  name : smartstock_replication
  host : 103.107.100.133
  port : 5432
  username : smartstock
  password : Bie8eesh1wuph5shaado
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/KF/SECURITY/kf-security.log
  base:
    path : http://localhost:9001/kf-api-logger