#============================================================================
# DATABASE
#============================================================================
db:
  name : test_security
  host : 180.250.242.163
  port : 5432
  username : postgres
  password : S1gm4etc2018!
  auto-reconnect : true
  ssl : false

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/KF/SECURITY/kf-security.log
  base:
    path : http://localhost:9001/kf-api-logger