#============================================================================
# SERVER
#============================================================================
server:
  port: 8000
  tomcat:
    max-threads : 2000
  servlet:
    context-path: /fj-api-logger

#============================================================================
# MONGO DB
#============================================================================
spring:
  application:
    name: fauzi-jenius-logger
  data:
    mongodb:
      repositories : ${db.repositories}
      host: ${db.host}
      port: ${db.port}
      database: ${db.name}
      authentication-database: ${db.authentication-database}
      username: ${db.username}
      password: ${db.password}
      uri : ${db.uri}
  rabbitmq:
    host : ${rabbitmq.host}
    port : ${rabbitmq.port}
    username : ${rabbitmq.username}
    password : ${rabbitmq.password}

#============================================================================
# DB
#============================================================================
db:
  name : fj-api-log
  host : 180.250.19.229
  port : 27017
  database : fj-api-log
  authentication-database : admin
  username : mongo
  password : mongoP@ssword
  repositories : true
  uri : mongodb://localhost/fj-api-log

#============================================================================
# LOGGING
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file : ${log.file.path}
  level:
    org.springframework.data: info

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/fj/logger/fj-api-logger.log


#============================================================================
# RABBIT MQ
#============================================================================
rabbitmq:
  host : 180.250.19.229
  port : 5672
  username : guest
  password : guest
  fanout:
    exchange:
      api-logger : fanout-exchange-api-logger
      jwt-logger : fanout-exchange-jwt-logger
      auth-logger : fanout-exchange-auth-logger
  queue :
    api-logger : queue-api-logger
    jwt-logger : queue-jwt-logger
    auth-logger : queue-auth-logger


#============================================================================
# SWAGGER
#============================================================================
swagger :
  vendor :
    name : Fauzi
    value : 1.0.0
  metadata :
    title : Api Logger
    description : Api Logger for Microservices Projects
    version : 1.0.0
    tos : This Documentation is Only Available on Development Phase
    license : Apache License Version 2.0
    license-url : https://www.apache.org/licenses/LICENSE-2.0
    contact :
      name : Achmad Fauzi
      url : https://github.com/KNIGHTMASTER
      email : fauzi.knightmaster.achmad@gmail.com

#============================================================================
#EUREKA
#============================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

#============================================================================
#INFO
#============================================================================
info:
  app:
    name: API Logger Application
    description: API for Logging Any Services
    version: 1.0.0

#============================================================================
# Async
#============================================================================
thread:
  corepoolsize: 100
  maxpoolsize: 200
  queuecapacity: 1000