#============================================================================
# SERVER
#============================================================================
server:
  port: 8080
  tomcat:
    max-threads : 2000

#============================================================================
# MONGO DB
#============================================================================
spring:
  application:
    name: fauzi-jenius-account
#  profiles :
#    active : local
  data:
    mongodb:
      repositories : ${db.repositories.enabled}
      host: ${db.host}
      port: ${db.port}
      database: ${db.name}
      authentication-database: ${db.authentication-database}
      username: ${db.username}
      password: ${db.password}
      uri : ${db.uri}

#============================================================================
# DB
#============================================================================
db:
  name : fauzi-account-db
  host : localhost
  port : 27017
  authentication-database : admin
#  username : mongo
#  password : mongoP@ssw0rd
  repositories :
    enabled : true
  uri : mongodb://localhost/fauzi-account-db

#============================================================================
# LOGGING
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file : ${log.file.path}
  level:
    org.springframework.data: info
    org.springframework.security.oauth2 : debug

#============================================================================
# LOG FILE
#============================================================================
log :
  file :
    path : /home/fauzi/fj-account/fj-account.log


#============================================================================
# OAUTH 2.0 | SSO
#============================================================================
security:
  basic:
    enabled: false
  oauth2:
    sso :
      loginPath : /login
    client:
      grant-type : password
      clientId: oc_client
      clientSecret: oc-secret
      accessTokenUri: http://localhost:9000/oauth/token
      userAuthorizationUri: http://localhost:9000/oauth/authorize
    resource:
      userInfoUri: http://localhost:9000/principal/me
      tokenInfoUri : http://localhost:9000/oauth/check_token

#============================================================================
# SWAGGER
#============================================================================
swagger :
  vendor :
    name : Fauzi
    value : 1.0.0
  metadata :
    title : Fauzi Account API
    description : Fauzi Account API
    version : 1.0.0
    tos : This Documentation is Only Available on Development Phase
    license : Apache License Version 2.0
    license-url : https://www.apache.org/licenses/LICENSE-2.0
    contact :
      name : Achmad Fauzi
      url : https://github.com/KNIGHTMASTER/fauzi-jenius
      email : fauzi.knightmaster.achmad@gmail.com